name = "scratchpad"
version = "0.1.0"
defaultTargets = ["scratchpad"]

[[lean_lib]]
name = "Scratchpad"

[[lean_exe]]
name = "scratchpad"
root = "Main"

[[require]]
name = "auto"
scope = "leanprover-community"
rev = "2c088e7617d6e2018386de23b5df3b127fae4634"
